#include "map.h"
#include "pacman.h"
#include <stdint.h>
#include <stdlib.h>

enum TileType board[MAP_HEIGHT][MAP_LENGTH];

void parse_map(Tile map[MAP_HEIGHT][MAP_LENGTH]){
	int row = 0;
	for (; row < MAP_HEIGHT; row++) {
		int col = 0;
		for (; col < MAP_LENGTH; col++) {
			map[row][col].type = board[row][col];
    }
  }
}

void place_power_pill(Game* game){
		int row = rand() % MAP_HEIGHT;
		int col = rand() % MAP_LENGTH;
		if (game->map[row][col].type == STANDARD_PILL)	{
				game->map[row][col].type = POWER_PILL;
				game->power_pills_count++;
		}
}

void place_power_pills(Game* game){
	int placed = 0;
	while (placed < POWER_PILLS_COUNT)	{
		place_power_pill(game);
		placed++;
	}
}

void generate_map(Game* game){
	parse_map( game->map );
	//TODO place pills
	place_power_pills(game); //FIXME
}

uint8_t is_a_pill(Tile* tile){
	if(tile->type == STANDARD_PILL || tile->type == POWER_PILL){
		return 1;
	} else {
		return 0;
	}
}

uint8_t get_tile_score(Tile* tile){
	switch(tile->type){
		case STANDARD_PILL:
			return STANDARD_PILL_SCORE;
		case POWER_PILL:
			return POWER_PILL_SCORE;
		default:
			return 0;
	}
}

enum TileType board[MAP_HEIGHT][MAP_LENGTH] = {
    {WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL}, 
    {WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL},
    {WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL},
    {WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL},
    {WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL},
    {WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL},
    {WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL},
    {WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL},
    {WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL},
    {WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, EMPTY_TILE, WALL, WALL, EMPTY_TILE, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL},
    {WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, EMPTY_TILE, WALL, WALL, EMPTY_TILE, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL},
    {WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL},
    {WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, EMPTY_TILE, WALL, WALL, WALL, EMPTY_TILE, EMPTY_TILE, WALL, WALL, WALL, EMPTY_TILE, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL},
    {WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, EMPTY_TILE, WALL, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, WALL, EMPTY_TILE, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL},
    {TELEPORT, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, STANDARD_PILL, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, WALL, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, WALL, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, STANDARD_PILL, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, TELEPORT},
    {WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, EMPTY_TILE, WALL, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, WALL, EMPTY_TILE, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL}, 
    {WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, EMPTY_TILE, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, EMPTY_TILE, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL},
    {WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL},
    {WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, EMPTY_TILE, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, EMPTY_TILE, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL},
    {WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, EMPTY_TILE, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, EMPTY_TILE, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL},
    {WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL},
    {WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL},
    {WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL},
    {WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL},
    {WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL},
    {WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL},
    {WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL},
    {WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL},
    {WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL},
    {WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL},
    {WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL}
};