#include "pacman.h"
#include <stdlib.h>
#include "../GLCD/GLCD.h"

#define MARGIN_LEFT 8
#define MARGIN_TOP 8

enum TileType board[MAP_HEIGHT][MAP_LENGTH] = {
    {WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL}, 
    {WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL},
    {WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL},
    {WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL},
    {WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL},
    {WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL},
    {WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL},
    {WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL},
    {WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL},
    {WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, EMPTY_TILE, WALL, WALL, EMPTY_TILE, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL},
    {WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, EMPTY_TILE, WALL, WALL, EMPTY_TILE, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL},
    {WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL},
    {WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, EMPTY_TILE, WALL, WALL, WALL, EMPTY_TILE, EMPTY_TILE, WALL, WALL, WALL, EMPTY_TILE, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL},
    {WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, EMPTY_TILE, WALL, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, WALL, EMPTY_TILE, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL},
    {TELEPORT, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, STANDARD_PILL, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, WALL, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, WALL, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, STANDARD_PILL, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, TELEPORT},
    {WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, EMPTY_TILE, WALL, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, WALL, EMPTY_TILE, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL}, 
    {WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, EMPTY_TILE, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, EMPTY_TILE, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL},
    {WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, EMPTY_TILE, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL},
    {WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, EMPTY_TILE, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, EMPTY_TILE, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL},
    {WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, EMPTY_TILE, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, EMPTY_TILE, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL},
    {WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL},
    {WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL},
    {WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL},
    {WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL},
    {WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL},
    {WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL},
    {WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL},
    {WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL},
    {WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL, WALL, STANDARD_PILL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, STANDARD_PILL, WALL},
    {WALL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, STANDARD_PILL, WALL},
    {WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL}
};

uint8_t is_a_pill(Tile* tile){
	if(tile->type == STANDARD_PILL || tile->type == POWER_PILL){
		return 1;
	} else {
		return 0;
	}
}

uint8_t get_tile_score(Tile* tile){
	switch(tile->type){
		case STANDARD_PILL:
			return STANDARD_PILL_SCORE;
		case POWER_PILL:
			return POWER_PILL_SCORE;
		default:
			return 0;
	}
}

void new_game(Game* game){
	game->state = PAUSED;
	generate_map(game->map);	
	game->score = 0;
	game->lives = 1;
	game->time = 60;
	
	game->standard_pills_count = STANDARD_PILLS_COUNT;
	game->power_pills_count = POWER_PILLS_COUNT;
	//TODO place pacman on the map
	
	game->pacman_x = PACMAN_INITIAL_POSITION_X;
	game->pacman_y = PACMAN_INITIAL_POSITION_Y;
	//game->map[game->pacman_y][game->pacman_x].type = PACMAN;
}

void update_game_state(Game* game) {
    if (game->lives == 0) {
        game->state = GAME_OVER;
    } else if (game->standard_pills_count == 0 && game->power_pills_count == 0) {
        game->state = WON;
    }
}

void draw_pacman(uint16_t row, uint16_t col){
	int i = 0;
	for(; i < 8; i++){
		int j = 0;
		for(; j < 8; j++){
			LCD_SetPoint(MARGIN_LEFT +8*col + j, MARGIN_TOP + 8*row + i , Yellow);
		}
	}
}

void display_tile(uint16_t row, uint16_t col, Tile* tile){
	int color = 0;
	switch(tile->type){
		case EMPTY_TILE:
			color = Black;
			break;
		case WALL:
			color = Blue;
			break;
		case STANDARD_PILL:
			color = White;
			break;
		case POWER_PILL:
			color = Red;
			break;
		case TELEPORT:
			color = Blue;
			break;
		case PACMAN:
			color = Yellow;
			break;
		
		default:
			break;
	}
	
	int i = 0;
	for(; i < 8; i++){
		int j = 0;
		for(; j < 8; j++){
			LCD_SetPoint(MARGIN_LEFT +8*col + j, MARGIN_TOP + 8*row + i , color);
		}
	}
}

void display_map(Tile map[MAP_HEIGHT][MAP_LENGTH]){
	uint16_t row = 0;
	for(; row < MAP_HEIGHT; row++){
		uint16_t col = 0;
		for(; col < MAP_LENGTH; col++){
			display_tile(row, col, &map[row][col]);
		}
	}
}


void display_game_info(Game* game){
	GUI_Text(0, 304, (uint8_t *) "Time: -- ", White, Black);
	
	GUI_Text(90, 304, (uint8_t *) "Lifes: - ", White, Black);
	
	GUI_Text(150, 304, (uint8_t *) "Score: ----", White, Black);
}


void start_game(Game* game){
  game->state = PLAYING;
}

void parse_map(Tile map[MAP_HEIGHT][MAP_LENGTH]){
	int row = 0;
	for (; row < MAP_HEIGHT; row++) {
		int col = 0;
		for (; col < MAP_LENGTH; col++) {
			map[row][col].type = board[row][col];
    }
  }
}

void place_power_pills(Tile map[MAP_HEIGHT][MAP_LENGTH]){
	int placed = 0;
	while (placed < POWER_PILLS_COUNT)	{
		int x = rand() % MAP_HEIGHT;
		int y = rand() % MAP_LENGTH;
		if (map[x][y].type == STANDARD_PILL)	{
				map[x][y].type = POWER_PILL;
				placed++;
		}
	}
}

void generate_map(Tile map[MAP_HEIGHT][MAP_LENGTH]){
	parse_map(map);
	//TODO place pills
	place_power_pills(map);
}

void add_life(Game* game){
	game->lives++;
}

void move_pacman(Game* game, int dx, int dy) {
    int new_x = game->pacman_x + dx;
    int new_y = game->pacman_y + dy;
    
    if (game->map[new_y][new_x].type != WALL) {
				// Replace the old tile with a new one
				game->map[game->pacman_y][game->pacman_x].type = EMPTY_TILE;
        game->pacman_x = new_x;
        game->pacman_y = new_y;
				// If the old tile was a pill update the game score
        if (is_a_pill(&game->map[new_y][new_x])) {
            game->score += get_tile_score(&game->map[new_y][new_x]);
            if (game->map[new_y][new_x].type == STANDARD_PILL) game->standard_pills_count--;
            else game->power_pills_count--;
        }
        game->map[new_y][new_x].type = PACMAN; // Update new position
		}
}

void move_pacman_up(Game* game){
	move_pacman(game, 0, -1);
}

void move_pacman_down(Game* game){
	move_pacman(game, 0, 1);
}

void move_pacman_left(Game* game){
	move_pacman(game, -1, 0);
}

void move_pacman_right(Game* game){
	move_pacman(game, 1, 0);
}